// Static reference list of major equities exchanges keyed by ISO 10383
// MIC code. Used to resolve raw source exchange labels (e.g. "Nasdaq",
// "NYSE", "LSE") to a canonical name / country / region for the
// Analytics > Sector > Exchange tracker.
//
// Order is roughly by global equity market cap. The IPO tracker only
// renders rows for exchanges that actually return data from the
// configured sources, so entries here without coverage will simply be
// hidden in the UI.

export type ExchangeRegion = "Americas" | "EMEA" | "APAC";

export type ExchangeRef = {
  mic: string;
  name: string;
  country: string;
  region: ExchangeRegion;
  website: string;
};

export const EXCHANGES: ExchangeRef[] = [
  // ── Americas ────────────────────────────────────────────────────────
  { mic: "XNYS", name: "New York Stock Exchange",         country: "United States",  region: "Americas", website: "https://www.nyse.com" },
  { mic: "XNAS", name: "Nasdaq",                           country: "United States",  region: "Americas", website: "https://www.nasdaq.com" },
  { mic: "ARCX", name: "NYSE Arca",                        country: "United States",  region: "Americas", website: "https://www.nyse.com" },
  { mic: "XASE", name: "NYSE American",                    country: "United States",  region: "Americas", website: "https://www.nyse.com" },
  { mic: "BATS", name: "Cboe BZX",                         country: "United States",  region: "Americas", website: "https://www.cboe.com" },
  { mic: "OTCM", name: "OTC Markets",                      country: "United States",  region: "Americas", website: "https://www.otcmarkets.com" },
  { mic: "XTSE", name: "Toronto Stock Exchange",           country: "Canada",         region: "Americas", website: "https://www.tsx.com" },
  { mic: "XTSX", name: "TSX Venture Exchange",             country: "Canada",         region: "Americas", website: "https://www.tsx.com" },
  { mic: "NEOE", name: "Cboe Canada (NEO)",                country: "Canada",         region: "Americas", website: "https://www.cboe.com" },
  { mic: "BVMF", name: "B3 (Brasil Bolsa Balcão)",         country: "Brazil",         region: "Americas", website: "https://www.b3.com.br" },
  { mic: "XMEX", name: "Bolsa Mexicana de Valores",        country: "Mexico",         region: "Americas", website: "https://www.bmv.com.mx" },
  { mic: "BIVA", name: "BIVA (Bolsa Institucional)",       country: "Mexico",         region: "Americas", website: "https://www.biva.mx" },
  { mic: "XBUE", name: "Bolsas y Mercados Argentinos",     country: "Argentina",      region: "Americas", website: "https://www.byma.com.ar" },
  { mic: "XSGO", name: "Santiago Stock Exchange",          country: "Chile",          region: "Americas", website: "https://www.bolsadesantiago.com" },
  { mic: "XBOG", name: "Colombia Stock Exchange (BVC)",    country: "Colombia",       region: "Americas", website: "https://www.bvc.com.co" },
  { mic: "XLIM", name: "Lima Stock Exchange",              country: "Peru",           region: "Americas", website: "https://www.bvl.com.pe" },
  { mic: "XCAR", name: "Caracas Stock Exchange",           country: "Venezuela",      region: "Americas", website: "http://www.bolsadecaracas.com" },
  { mic: "XBVS", name: "El Salvador Stock Exchange",       country: "El Salvador",    region: "Americas", website: "https://www.bolsadevalores.com.sv" },

  // ── EMEA ────────────────────────────────────────────────────────────
  { mic: "XLON", name: "London Stock Exchange",            country: "United Kingdom", region: "EMEA",     website: "https://www.londonstockexchange.com" },
  { mic: "AIMX", name: "London AIM",                       country: "United Kingdom", region: "EMEA",     website: "https://www.londonstockexchange.com/raise-finance/equity/aim" },
  { mic: "XPAR", name: "Euronext Paris",                   country: "France",         region: "EMEA",     website: "https://www.euronext.com" },
  { mic: "XAMS", name: "Euronext Amsterdam",               country: "Netherlands",    region: "EMEA",     website: "https://www.euronext.com" },
  { mic: "XBRU", name: "Euronext Brussels",                country: "Belgium",        region: "EMEA",     website: "https://www.euronext.com" },
  { mic: "XLIS", name: "Euronext Lisbon",                  country: "Portugal",       region: "EMEA",     website: "https://www.euronext.com" },
  { mic: "MTAA", name: "Euronext Milan",                   country: "Italy",          region: "EMEA",     website: "https://www.euronext.com" },
  { mic: "XOSL", name: "Euronext Oslo",                    country: "Norway",         region: "EMEA",     website: "https://www.euronext.com" },
  { mic: "XMSM", name: "Euronext Dublin",                  country: "Ireland",        region: "EMEA",     website: "https://www.euronext.com" },
  { mic: "XETR", name: "Deutsche Börse Xetra",             country: "Germany",        region: "EMEA",     website: "https://www.deutsche-boerse.com" },
  { mic: "XFRA", name: "Frankfurt Stock Exchange",         country: "Germany",        region: "EMEA",     website: "https://www.boerse-frankfurt.de" },
  { mic: "XSWX", name: "SIX Swiss Exchange",               country: "Switzerland",    region: "EMEA",     website: "https://www.six-group.com" },
  { mic: "XMAD", name: "BME Spanish Exchanges",            country: "Spain",          region: "EMEA",     website: "https://www.bolsasymercados.es" },
  { mic: "XWBO", name: "Vienna Stock Exchange",            country: "Austria",        region: "EMEA",     website: "https://www.wienerborse.at" },
  { mic: "XSTO", name: "Nasdaq Stockholm",                 country: "Sweden",         region: "EMEA",     website: "https://www.nasdaqomxnordic.com" },
  { mic: "FNSE", name: "Nasdaq First North Stockholm",     country: "Sweden",         region: "EMEA",     website: "https://www.nasdaqomxnordic.com" },
  { mic: "XCSE", name: "Nasdaq Copenhagen",                country: "Denmark",        region: "EMEA",     website: "https://www.nasdaqomxnordic.com" },
  { mic: "XHEL", name: "Nasdaq Helsinki",                  country: "Finland",        region: "EMEA",     website: "https://www.nasdaqomxnordic.com" },
  { mic: "XICE", name: "Nasdaq Iceland",                   country: "Iceland",        region: "EMEA",     website: "https://www.nasdaqomxnordic.com" },
  { mic: "XWAR", name: "Warsaw Stock Exchange",            country: "Poland",         region: "EMEA",     website: "https://www.gpw.pl" },
  { mic: "XPRA", name: "Prague Stock Exchange",            country: "Czechia",        region: "EMEA",     website: "https://www.pse.cz" },
  { mic: "XBUD", name: "Budapest Stock Exchange",          country: "Hungary",        region: "EMEA",     website: "https://www.bse.hu" },
  { mic: "XBSE", name: "Bucharest Stock Exchange",         country: "Romania",        region: "EMEA",     website: "https://www.bvb.ro" },
  { mic: "XATH", name: "Athens Stock Exchange",            country: "Greece",         region: "EMEA",     website: "https://www.athexgroup.gr" },
  { mic: "XCYS", name: "Cyprus Stock Exchange",            country: "Cyprus",         region: "EMEA",     website: "https://www.cse.com.cy" },
  { mic: "XIST", name: "Borsa Istanbul",                   country: "Turkey",         region: "EMEA",     website: "https://www.borsaistanbul.com" },
  { mic: "MISX", name: "Moscow Exchange",                  country: "Russia",         region: "EMEA",     website: "https://www.moex.com" },
  { mic: "XKIE", name: "Ukrainian Exchange",               country: "Ukraine",        region: "EMEA",     website: "https://ux.ua" },
  { mic: "XTAE", name: "Tel Aviv Stock Exchange",          country: "Israel",         region: "EMEA",     website: "https://www.tase.co.il" },
  { mic: "XSAU", name: "Saudi Exchange (Tadawul)",         country: "Saudi Arabia",   region: "EMEA",     website: "https://www.saudiexchange.sa" },
  { mic: "DSMD", name: "Qatar Stock Exchange",             country: "Qatar",          region: "EMEA",     website: "https://www.qe.com.qa" },
  { mic: "XADS", name: "Abu Dhabi Securities Exchange",    country: "United Arab Emirates", region: "EMEA", website: "https://www.adx.ae" },
  { mic: "XDFM", name: "Dubai Financial Market",           country: "United Arab Emirates", region: "EMEA", website: "https://www.dfm.ae" },
  { mic: "XKUW", name: "Boursa Kuwait",                    country: "Kuwait",         region: "EMEA",     website: "https://www.boursakuwait.com.kw" },
  { mic: "XBAH", name: "Bahrain Bourse",                   country: "Bahrain",        region: "EMEA",     website: "https://www.bahrainbourse.com" },
  { mic: "XMUS", name: "Muscat Securities Market",         country: "Oman",           region: "EMEA",     website: "https://www.msx.om" },
  { mic: "XCAS", name: "Casablanca Stock Exchange",        country: "Morocco",        region: "EMEA",     website: "https://www.casablanca-bourse.com" },
  { mic: "XCAI", name: "Egyptian Exchange (EGX)",          country: "Egypt",          region: "EMEA",     website: "https://www.egx.com.eg" },
  { mic: "XJSE", name: "Johannesburg Stock Exchange",      country: "South Africa",   region: "EMEA",     website: "https://www.jse.co.za" },
  { mic: "XNSA", name: "Nigerian Exchange (NGX)",          country: "Nigeria",        region: "EMEA",     website: "https://ngxgroup.com" },
  { mic: "XNAI", name: "Nairobi Securities Exchange",      country: "Kenya",          region: "EMEA",     website: "https://www.nse.co.ke" },
  { mic: "XGHA", name: "Ghana Stock Exchange",             country: "Ghana",          region: "EMEA",     website: "https://gse.com.gh" },
  { mic: "XBOT", name: "Botswana Stock Exchange",          country: "Botswana",       region: "EMEA",     website: "https://www.bse.co.bw" },
  { mic: "XMAU", name: "Stock Exchange of Mauritius",      country: "Mauritius",      region: "EMEA",     website: "https://www.stockexchangeofmauritius.com" },
  { mic: "XBEY", name: "Beirut Stock Exchange",            country: "Lebanon",        region: "EMEA",     website: "https://www.bse.com.lb" },
  { mic: "XAMM", name: "Amman Stock Exchange",             country: "Jordan",         region: "EMEA",     website: "https://www.exchange.jo" },
  { mic: "XTUN", name: "Tunis Stock Exchange",             country: "Tunisia",        region: "EMEA",     website: "https://www.bvmt.com.tn" },
  { mic: "XBUL", name: "Bulgarian Stock Exchange",         country: "Bulgaria",       region: "EMEA",     website: "https://www.bse-sofia.bg" },
  { mic: "XZAG", name: "Zagreb Stock Exchange",            country: "Croatia",        region: "EMEA",     website: "https://www.zse.hr" },
  { mic: "XTAL", name: "Nasdaq Tallinn",                   country: "Estonia",        region: "EMEA",     website: "https://www.nasdaqbaltic.com" },
  { mic: "XRIS", name: "Nasdaq Riga",                      country: "Latvia",         region: "EMEA",     website: "https://www.nasdaqbaltic.com" },
  { mic: "XLIT", name: "Nasdaq Vilnius",                   country: "Lithuania",      region: "EMEA",     website: "https://www.nasdaqbaltic.com" },
  { mic: "XLUX", name: "Luxembourg Stock Exchange",        country: "Luxembourg",     region: "EMEA",     website: "https://www.luxse.com" },
  { mic: "XMAL", name: "Malta Stock Exchange",             country: "Malta",          region: "EMEA",     website: "https://www.borzamalta.com.mt" },
  { mic: "XBRA", name: "Bratislava Stock Exchange",        country: "Slovakia",       region: "EMEA",     website: "https://www.bsse.sk" },
  { mic: "XLJU", name: "Ljubljana Stock Exchange",         country: "Slovenia",       region: "EMEA",     website: "https://ljse.si" },

  // ── APAC ────────────────────────────────────────────────────────────
  { mic: "XTKS", name: "Tokyo Stock Exchange",             country: "Japan",          region: "APAC",     website: "https://www.jpx.co.jp" },
  { mic: "XNGO", name: "Nagoya Stock Exchange",            country: "Japan",          region: "APAC",     website: "https://www.nse.or.jp" },
  { mic: "XFKA", name: "Fukuoka Stock Exchange",           country: "Japan",          region: "APAC",     website: "https://www.fse.or.jp" },
  { mic: "XSAP", name: "Sapporo Stock Exchange",           country: "Japan",          region: "APAC",     website: "https://www.sse.or.jp" },
  { mic: "XSHG", name: "Shanghai Stock Exchange",          country: "China",          region: "APAC",     website: "http://english.sse.com.cn" },
  { mic: "XSHE", name: "Shenzhen Stock Exchange",          country: "China",          region: "APAC",     website: "http://www.szse.cn/English/" },
  { mic: "BJSE", name: "Beijing Stock Exchange",           country: "China",          region: "APAC",     website: "https://www.bse.cn" },
  { mic: "XHKG", name: "Hong Kong Stock Exchange",         country: "Hong Kong",      region: "APAC",     website: "https://www.hkex.com.hk" },
  { mic: "XTAI", name: "Taiwan Stock Exchange",            country: "Taiwan",         region: "APAC",     website: "https://www.twse.com.tw" },
  { mic: "ROCO", name: "Taipei Exchange",                  country: "Taiwan",         region: "APAC",     website: "https://www.tpex.org.tw" },
  { mic: "XKRX", name: "Korea Exchange (KOSPI)",           country: "South Korea",    region: "APAC",     website: "http://global.krx.co.kr" },
  { mic: "XKOS", name: "KOSDAQ",                           country: "South Korea",    region: "APAC",     website: "http://global.krx.co.kr" },
  { mic: "XSES", name: "Singapore Exchange",               country: "Singapore",      region: "APAC",     website: "https://www.sgx.com" },
  { mic: "XKLS", name: "Bursa Malaysia",                   country: "Malaysia",       region: "APAC",     website: "https://www.bursamalaysia.com" },
  { mic: "XBKK", name: "Stock Exchange of Thailand",       country: "Thailand",       region: "APAC",     website: "https://www.set.or.th" },
  { mic: "XIDX", name: "Indonesia Stock Exchange",         country: "Indonesia",      region: "APAC",     website: "https://www.idx.co.id" },
  { mic: "XPHS", name: "Philippine Stock Exchange",        country: "Philippines",    region: "APAC",     website: "https://www.pse.com.ph" },
  { mic: "XSTC", name: "Ho Chi Minh Stock Exchange",       country: "Vietnam",        region: "APAC",     website: "https://www.hsx.vn" },
  { mic: "HSTC", name: "Hanoi Stock Exchange",             country: "Vietnam",        region: "APAC",     website: "https://hnx.vn" },
  { mic: "XBOM", name: "BSE (Bombay Stock Exchange)",      country: "India",          region: "APAC",     website: "https://www.bseindia.com" },
  { mic: "XNSE", name: "National Stock Exchange of India", country: "India",          region: "APAC",     website: "https://www.nseindia.com" },
  { mic: "XASX", name: "Australian Securities Exchange",   country: "Australia",      region: "APAC",     website: "https://www.asx.com.au" },
  { mic: "CHIA", name: "Cboe Australia (Chi-X)",           country: "Australia",      region: "APAC",     website: "https://www.cboe.com" },
  { mic: "XNZE", name: "NZX (New Zealand Exchange)",       country: "New Zealand",    region: "APAC",     website: "https://www.nzx.com" },
  { mic: "XKAR", name: "Pakistan Stock Exchange",          country: "Pakistan",       region: "APAC",     website: "https://www.psx.com.pk" },
  { mic: "XCOL", name: "Colombo Stock Exchange",           country: "Sri Lanka",      region: "APAC",     website: "https://www.cse.lk" },
  { mic: "XDHA", name: "Dhaka Stock Exchange",             country: "Bangladesh",     region: "APAC",     website: "https://www.dsebd.org" },
  { mic: "XCHG", name: "Chittagong Stock Exchange",        country: "Bangladesh",     region: "APAC",     website: "https://www.cse.com.bd" },
  { mic: "XNEP", name: "Nepal Stock Exchange",             country: "Nepal",          region: "APAC",     website: "https://www.nepalstock.com.np" },
  { mic: "XMNB", name: "Mongolian Stock Exchange",         country: "Mongolia",       region: "APAC",     website: "https://www.mse.mn" },
  { mic: "XCSX", name: "Cambodia Securities Exchange",     country: "Cambodia",       region: "APAC",     website: "https://csx.com.kh" },
  { mic: "XLAO", name: "Lao Securities Exchange",          country: "Laos",           region: "APAC",     website: "https://www.lsx.com.la" },
  { mic: "XYSX", name: "Yangon Stock Exchange",            country: "Myanmar",        region: "APAC",     website: "https://ysx-mm.com" },
];

const BY_MIC = new Map<string, ExchangeRef>(
  EXCHANGES.map((e) => [e.mic, e]),
);

export function getExchange(mic: string): ExchangeRef | undefined {
  return BY_MIC.get(mic);
}

// Source labels we encounter from SEC EDGAR / Yahoo / etc., mapped to
// canonical MICs above. Lookup is case-insensitive.
const SOURCE_TO_MIC: Record<string, string> = {
  // SEC EDGAR `company_tickers_exchange.json` values
  "nasdaq": "XNAS",
  "nyse": "XNYS",
  "nyse arca": "ARCX",
  "nyse american": "XASE",
  "cboe": "BATS",
  "cboe bzx": "BATS",
  "otc": "OTCM",
  "otc markets": "OTCM",
  "otcm": "OTCM",
  // Yahoo / common labels
  "tsx": "XTSE",
  "toronto": "XTSE",
  "tsx venture": "XTSX",
  "tsxv": "XTSX",
  "b3": "BVMF",
  "bovespa": "BVMF",
  "lse": "XLON",
  "london": "XLON",
  "aim": "AIMX",
  "euronext paris": "XPAR",
  "paris": "XPAR",
  "euronext amsterdam": "XAMS",
  "amsterdam": "XAMS",
  "euronext brussels": "XBRU",
  "brussels": "XBRU",
  "euronext lisbon": "XLIS",
  "lisbon": "XLIS",
  "euronext milan": "MTAA",
  "milan": "MTAA",
  "borsa italiana": "MTAA",
  "euronext oslo": "XOSL",
  "oslo": "XOSL",
  "euronext dublin": "XMSM",
  "dublin": "XMSM",
  "xetra": "XETR",
  "deutsche börse": "XETR",
  "deutsche boerse": "XETR",
  "frankfurt": "XFRA",
  "six": "XSWX",
  "six swiss": "XSWX",
  "swiss": "XSWX",
  "bme": "XMAD",
  "madrid": "XMAD",
  "vienna": "XWBO",
  "stockholm": "XSTO",
  "copenhagen": "XCSE",
  "helsinki": "XHEL",
  "warsaw": "XWAR",
  "athens": "XATH",
  "istanbul": "XIST",
  "borsa istanbul": "XIST",
  "moex": "MISX",
  "moscow": "MISX",
  "tase": "XTAE",
  "tel aviv": "XTAE",
  "tadawul": "XSAU",
  "saudi": "XSAU",
  "adx": "XADS",
  "abu dhabi": "XADS",
  "dfm": "XDFM",
  "dubai": "XDFM",
  "qse": "DSMD",
  "qatar": "DSMD",
  "jse": "XJSE",
  "johannesburg": "XJSE",
  "ngx": "XNSA",
  "nigerian": "XNSA",
  "nse kenya": "XNAI",
  "nairobi": "XNAI",
  "egx": "XCAI",
  "egyptian": "XCAI",
  "casablanca": "XCAS",
  // APAC
  "tse": "XTKS",
  "tokyo": "XTKS",
  "jpx": "XTKS",
  "nagoya": "XNGO",
  "shanghai": "XSHG",
  "sse": "XSHG",
  "shenzhen": "XSHE",
  "szse": "XSHE",
  "beijing": "BJSE",
  "bse china": "BJSE",
  "hkex": "XHKG",
  "hong kong": "XHKG",
  "twse": "XTAI",
  "taiwan": "XTAI",
  "tpex": "ROCO",
  "krx": "XKRX",
  "kospi": "XKRX",
  "kosdaq": "XKOS",
  "sgx": "XSES",
  "singapore": "XSES",
  "bursa malaysia": "XKLS",
  "klse": "XKLS",
  "set": "XBKK",
  "bangkok": "XBKK",
  "idx": "XIDX",
  "indonesia": "XIDX",
  "pse": "XPHS",
  "philippine": "XPHS",
  "hose": "XSTC",
  "ho chi minh": "XSTC",
  "hnx": "HSTC",
  "hanoi": "HSTC",
  "bse india": "XBOM",
  "bombay": "XBOM",
  "nse india": "XNSE",
  "asx": "XASX",
  "australian": "XASX",
  "nzx": "XNZE",
  "new zealand": "XNZE",
  "psx": "XKAR",
  "karachi": "XKAR",
  "cse sri lanka": "XCOL",
  "colombo": "XCOL",
  "dhaka": "XDHA",

  // LSE (RNS) market labels
  "main market": "XLON",
  "high growth segment": "XLON",
  // HKEX market labels
  "main board": "XHKG",
  "gem": "XHKG",
  // JPX/TSE market segment labels (post-2022 restructure)
  "prime market": "XTKS",
  "standard market": "XTKS",
  "growth market": "XTKS",
  // TMX market labels
  "tmx": "XTSE",
  "toronto stock exchange": "XTSE",
  "tsx venture exchange": "XTSX",
  // ESMA / Euronext market labels we may encounter
  "euronext": "XPAR",
  "euronext growth paris": "XPAR",
  "euronext growth milan": "MTAA",
  "euronext access paris": "XPAR",
};

// ESMA / regulators use ISO 3166-1 alpha-2 country codes. Map them to
// the primary equities MIC for that country. Used as a fallback when
// a raw exchange label can't be resolved directly.
const COUNTRY_TO_MIC: Record<string, string> = {
  AT: "XWBO",
  BE: "XBRU",
  BG: "XBUL",
  HR: "XZAG",
  CY: "XCYS",
  CZ: "XPRA",
  DK: "XCSE",
  EE: "XTAL",
  FI: "XHEL",
  FR: "XPAR",
  DE: "XETR",
  GR: "XATH",
  HU: "XBUD",
  IS: "XICE",
  IE: "XMSM",
  IT: "MTAA",
  LV: "XRIS",
  LT: "XLIT",
  LU: "XLUX",
  MT: "XMAL",
  NL: "XAMS",
  NO: "XOSL",
  PL: "XWAR",
  PT: "XLIS",
  RO: "XBSE",
  SK: "XBRA",
  SI: "XLJU",
  ES: "XMAD",
  SE: "XSTO",
  GB: "XLON",
  CH: "XSWX",
  // Useful non-EU codes
  US: "XNAS",
  CA: "XTSE",
  AU: "XASX",
  JP: "XTKS",
  HK: "XHKG",
  SG: "XSES",
  IN: "XNSE",
  KR: "XKRX",
  ZA: "XJSE",
  BR: "BVMF",
  MX: "XMEX",
  IL: "XTAE",
  TR: "XIST",
  SA: "XSAU",
  AE: "XADS",
};

export function resolveMicFromCountry(code: string | null | undefined): string | null {
  if (!code) return null;
  const k = code.trim().toUpperCase();
  return COUNTRY_TO_MIC[k] ?? null;
}

export function resolveMicFromLabel(label: string | null | undefined): string | null {
  if (!label) return null;
  const key = label.trim().toLowerCase();
  if (!key) return null;
  if (BY_MIC.has(key.toUpperCase())) return key.toUpperCase();
  return SOURCE_TO_MIC[key] ?? null;
}
